package config

import "time"

const (
	ENV_VERIFICATION_CODE_LIFETIME          = "VERIFICATION_CODE_LIFETIME"
	ENV_TOKEN_EXPIRATION_MIN                = "TOKEN_EXPIRATION_MIN"
	ENV_TOKEN_INVITATION_LIFETIME           = "INVITATION_TOKEN_LIFETIME"
	ENV_TOKEN_CONTACT_VERIFICATION_LIFETIME = "CONTACT_VERIFICATION_TOKEN_LIFETIME"

	ENV_USE_NO_CURSOR_TIMEOUT                   = "USE_NO_CURSOR_TIMEOUT"
	ENV_SEND_REMINDER_TO_UNVERIFIED_USERS_AFTER = "SEND_REMINDER_TO_UNVERIFIED_USERS_AFTER"
	ENV_NOTIFY_INACTIVE_USERS_AFTER             = "NOTIFY_INACTIVE_USERS_AFTER"
	ENV_DELETE_ACCOUNT_AFTER_NOTIFYING_USER     = "DELETE_ACCOUNT_AFTER_NOTIFYING_USER"

	ENV_WEEKDAY_ASSIGNATION_WEIGHTS = "WEEKDAY_ASSIGNATION_WEIGHTS"

	ENV_USER_MANAGEMENT_LISTEN_PORT = "USER_MANAGEMENT_LISTEN_PORT"
	ENV_ADDR_MESSAGING_SERVICE      = "ADDR_MESSAGING_SERVICE"
	ENV_ADDR_LOGGING_SERVICE        = "ADDR_LOGGING_SERVICE"
	ENV_ADDR_STUDY_SERVICE          = "ADDR_STUDY_SERVICE"

	ENV_NEW_USER_RATE_LIMIT             = "NEW_USER_RATE_LIMIT"
	ENV_CLEAN_UP_UNVERIFIED_USERS_AFTER = "CLEAN_UP_UNVERIFIED_USERS_AFTER"

	ENV_DISABLE_TIMER_TASK = "DISABLE_TIMER_TASK"

	ENV_LOG_LEVEL = "LOG_LEVEL"
)

const (
	defaultVerificationCodeLifetime         = 15 * 60 // for 2FA 6 digit code
	defaultTokenExpirationMin               = 55
	defaultInvitationTokenLifetime          = time.Hour * 24 * 7
	defaultContactVerificationTokenLifetime = time.Hour * 24 * 30
	defaultNotifyInactiveUsersAfter         = 0
	defaultDeleteAccountAfterNotifyingUser  = 0
)
